# Generated by Django 2.0.6 on 2022-06-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courserec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
